import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono, ABeeZee, Zilla_Slab } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const jetBrains_Mono = JetBrains_Mono({ subsets: ['latin']});

export const aBeeZee = ABeeZee({ subsets: ['latin'], weight: ['400'],});

export const zilla_Slab = Zilla_Slab({ subsets: ['latin'], weight: ['400'],});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}